services:
  - type: web
    name: shuttle-bus-app
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
  - type: postgres
    name: shuttle-bus-db
    plan: free
